# Importing and Exporting Numpy Arrays
> To or from either npy file or csv file

In [2]:
import numpy as np

In [3]:
numpy_arr = np.random.randint(5, 30, size=(4,5)) #generate a random 2d array

### For .npy file

Exporting in .npy file (numpy file)

In [11]:
np.save("exported_numpy_array.npy", numpy_arr) #numbers exported are in floating point numbers

importing from .npy file (numpy file)

In [5]:
array_frm_npy = np.load("exported_numpy_array.npy")
print(array_frm_npy)

[[19 21  7 27  8]
 [15 18  9 12 15]
 [29  5 29 22 17]
 [17 29 19 14 25]]


### For .csv file

Exporting to .csv file

In [10]:
np.savetxt("exported_numpy_array.csv", numpy_arr, delimiter=",")#numbers exported are in floating point numbers

Importing array from .csv file

In [9]:
array_frm_csv = np.loadtxt("exported_numpy_array.csv", delimiter=",")
print(array_frm_csv)

[[19. 21.  7. 27.  8.]
 [15. 18.  9. 12. 15.]
 [29.  5. 29. 22. 17.]
 [17. 29. 19. 14. 25.]]
