Arrays can be used in arithmentic calculations since they are matrices

In [2]:
import numpy as np

In [4]:
array1 = np.array([23,4,6])
array2 = np.array([9,8,3])

In [5]:
sumMatrix = array1 + array2 #simple arithmetics can be done with array (if you do this with default python list-type objects, it will just concatenate it)
print(sumMatrix)

[32 12  9]


In [7]:
print(array1 / array2) #divide

[2.55555556 0.5        2.        ]


In [10]:
print(array1 * array2) #multiply

[207  32  18]


**You can perform arithmetics on arrays of different shapes**
> BUT one of the arrays must be a simple shape of either single row or single column

In [20]:
array3 = np.array([[8,4,5],
                   [23,9,2]])
array4 = np.array([[3],
                   [4]]) #single column array

print(array3 + array4)

[[11  7  8]
 [27 13  6]]


In [21]:
array5 = np.array([[8,4,5],
                   [23,9,2]])
array6 = np.array([3,9,1]) #single row array

print(array5 + array6)

[[11 13  6]
 [26 18  3]]


Youc can perform dot product on two arrays

In [6]:
arr_1 = np.array([[1,3,4,2],
                  [9,6,8,3]])

arr_2 = np.array([[7,4,6,9],
                  [3,1,5,7],
                  [3,1,5,7]]).T #transpose this so that the shape will become (4,2) so that we can do dot product operation, else it'll throw an error becuase the shape of the cols of arr_1 has to be equal to the shae of the rows of arr_2

In [7]:
dot_matrix = np.dot(arr_1, arr_2)
dot_matrix

array([[ 61,  40,  40],
       [162,  94,  94]])

**Additional Example of Dot pProduct**

We want to calculate the total weekly sales of a store  
**NOTE:** This is just to visualise a dot product. Dot product is not meant to be used for this as it even gives **wrong result** from the expected value _(instead do your typical multiplication and addition)_

![table in excel](./assets/images/nut_butter_sales_table_pic.png)

In [17]:
units_sold_data = np.array([[2,7,1],
                       [9,4,16],
                       [11,14,18],
                       [13,13,16],
                       [15,18,9]]) #represneting the daily number of sales of Almond, Peanut Butter and Cashew Butter respectively (mon - Fri)

prices_data = np.array([[12,8,10]]) #prices of each cashew, Peanut Butter, and Almond respectively (the image's layout is wrong and will lead to wrong calculations when we transpose this array)

In [19]:
import pandas as pd

In [32]:
#create dataframe table for better visualisation
daily_sales = pd.DataFrame(units_sold_data, index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], columns=["Almond", "Peanut butter", "Cashew Butter"])
prices_table = pd.DataFrame(prices_data, index=["Price ($)"], columns=["Cashew Butter", "Peanut butter", "Almond"])

In [33]:
print(daily_sales, end="\n\n")
print(prices_table)

           Almond  Peanut butter  Cashew Butter
Monday          2              7              1
Tuesday         9              4             16
Wednesday      11             14             18
Thursday       13             13             16
Friday         15             18              9

           Cashew Butter  Peanut butter  Almond
Price ($)             12              8      10


Lets calculate the total sales per day for the whole week using dot product

In [37]:
total_sales_daily = np.dot(daily_sales,prices_table.T)
total_sales_col = pd.DataFrame(total_sales_daily, index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], columns=["Total Sales ($)"]) #Total sales daily that will be returned is wrong (it returns the Dot product instead)
total_sales_col

Total Sales ($)
Monday                  90
Tuesday                300
Wednesday              424
Thursday               420
Friday                 414

Merge the two dataframes

In [39]:
daily_sales = pd.concat([daily_sales, total_sales_col], axis = 1)
daily_sales

Almond  Peanut butter  Cashew Butter  Total Sales ($)
Monday          2              7              1               90
Tuesday         9              4             16              300
Wednesday      11             14             18              424
Thursday       13             13             16              420
Friday         15             18              9              414