# Logical Operations with Numpy Arrays

In [1]:
import numpy as np

In [10]:
array_1 = np.array([3,5,7,2])
array_2 = np.array([[4,1,6,9],
                    [0,5,7,3]])

You can compare multiple arrays and perform logical operations. 

In [ ]:
array_1 > array_2  #The result is a boolean array of the same shape as the highest-shaped array in the expression

array([[False,  True,  True, False],
       [ True, False, False, False]])

You can compare array to a number

In [8]:
array_1 > 2

array([ True,  True,  True, False])

In [9]:
3 < array_1

array([False,  True,  True, False])

You can execute equality logical expressions

In [12]:
array_1 == array_2

array([[False, False, False, False],
       [False,  True,  True, False]])