Arrays can be used in arithmentic calculations since they are matrices

In [1]:
import numpy as np

In [4]:
array1 = np.array([23,4,6])
array2 = np.array([9,8,3])

In [5]:
sumMatrix = array1 + array2 #simple arithmetics can be done with array (if you do this with default python list-type objects, it will just concatenate it)
print(sumMatrix)

[32 12  9]


In [7]:
print(array1 / array2) #divide

[2.55555556 0.5        2.        ]


In [10]:
print(array1 * array2) #multiply

[207  32  18]


**You can perform arithmetics on arrays of different shapes**
> BUT one of the arrays must be a simple shape of either single row or single column

In [20]:
array3 = np.array([[8,4,5],
                   [23,9,2]])
array4 = np.array([[3],
                   [4]]) #single column array

print(array3 + array4)

[[11  7  8]
 [27 13  6]]


In [21]:
array5 = np.array([[8,4,5],
                   [23,9,2]])
array6 = np.array([3,9,1]) #single row array

print(array5 + array6)

[[11 13  6]
 [26 18  3]]
