In [1]:
import numpy as np

Creating Array object

In [3]:
myArray = np.array([23,5,42])
print(myArray)
print(f"The datatype: {myArray.dtype}") #the shows the general datatype of the array (as long as all elements are the same data type, else it will show it as "object")

[23  5 42]
The datatype: int64


In [4]:
array_2D = np.array([[133,443,55],
                     [49,5,23]])
print(array_2D)
print(f"The Shape: {array_2D.shape}") #this returns the dimension (i.e. number of rows, columns, layers) of the array (this is returned as a tuple). In this case, its (2,3)
print(f"The number of Dimensions: {array_2D.ndim}") #this returns the number of layers the array has (in this case, its 2)
print(f"The number of Elements: {array_2D.size}") #this returns the total number of elements in the array (in this case, its 6)

[[133 443  55]
 [ 49   5  23]]
The Shape: (2, 3)
The number of Dimensions: 2
The number of Elements: 6


> Multidimensional arrays must have consistent shape accross every layer i.e. if row1 has 3 columns, then row2 must have 3 columns (else it becomes **inhomogeneous** which isn't allowed)

In [5]:
array_2D_inhomogeneous = np.array([[1,2,3],
                                   [4,5,6]])

### Data Type (and Dynamic Type Casting)
> Numpy arrays do dynamic type casting e.g. if some elments in the array are strings, then rest of the elements are cast to strings automatically for uniformity of the array.

In [6]:
array_2D_new = np.array([[23,56,7],
                         [4,"1",8]])
print(array_2D.dtype)
print(type(array_2D_new[0][0]))

int64
<class 'numpy.str_'>


> You can declare type cast when creating the array to convert all element to the specified type cast

In [7]:
array_2D_new2 = np.array([[23,56,7],
                         [4,"1",8]], dtype="int64") #this will ensure all elements are casted to int64 if they aren't already (provided they can be convert)
print(array_2D_new2.dtype)
print(array_2D_new2[1,1].dtype) #as shown here, the string "1" was converted to int 64

int64
int64


Type casting array elements to string

In [8]:
array_2D_new2_str = np.array([[23,56,7],
                              [4,"1",8]], dtype="<U3") #the "<U3" syntax is an optimised way of memory allocation by saying that the elements should be converted to string of less than 3 chars (since the numbers are maximum of 2 characters)
print(array_2D_new2_str.dtype)

<U3


> When complex elements (like dictionaries) are in an array, the array is formated as "object" since those are not primitive types and cannot be casted

In [9]:
dict = {"1": "23"}
array_2D_new3 = np.array([[23,56,7],
                          [4,dict,8]])
print(array_2D_new3.dtype)

object


### Creating Array with prefilled default values

In [10]:
#using the np.full() function, provide the shape (as tuple or int) and the default value
vector3 = np.full(3, 0) #. e.g. This creates a 1D array of 3 elements filled with "0"
print(f"1D: \n{vector3}", end="\n\n")

vector3_2D = np.full((2,3), 9) #this creates a 2D array of 2 rows and 3 columns filled with "9"
print(f"2D: \n{vector3_2D}")

1D: 
[0 0 0]

2D: 
[[9 9 9]
 [9 9 9]]


You can use other functions for providing default prefilled arrays with singular numbers like 0 or 1

In [11]:
#with these functions just provide the shape as the value is predefined depending on the function
vector3_new0 = np.zeros((2,3)) #this creates a array of 2 by 3 filled with "0" (float type)
vector3_new1 = np.ones((2,3)) #this creates a array of 2 by 3 filled with "1" (float type)

print(vector3_new0)

[[0. 0. 0.]
 [0. 0. 0.]]


You can prefil with **random** numbers

In [17]:
rand_vect = np.random.randint(5,20,size=(2,3)) #this will create a 2 x 3 array filled with random numbers between 5 and 20
print(rand_vect)

[[ 9 13 16]
 [16 15 16]]


Random number type 2

In [ ]:
x_array = np.random.random(50) * 20 #this generates 50 random numbers that ranges from 0.0 - 1.0 (the default randome behaviour of Python), then multiply each by 20
print(x_array)

[1.28728398e-02 1.77268416e+01 3.78993512e-02 1.67682022e+01
 9.55542343e+00 1.69913717e+01 6.47738368e+00 5.09823822e+00
 9.80974238e+00 8.84236896e+00 2.94782343e+00 1.25379132e+01
 9.07997331e+00 9.61462447e+00 7.91582837e+00 8.73154341e+00
 1.02418965e+01 1.71726242e+01 1.64732509e+01 1.27188218e+01
 1.55949410e+01 1.00604288e+01 6.01777518e+00 1.84897180e+01
 1.02253688e+01 1.28030961e+01 1.77695844e+01 1.53941348e+01
 1.50520880e+01 9.31634294e+00 1.94792345e+01 1.41690731e+00
 1.04662451e+01 1.59583583e+00 1.65971716e+01 1.14531169e+01
 1.40393611e+01 1.45504267e+01 1.87091927e+01 1.68033572e+01
 2.03409411e-01 1.05383167e+01 8.42869398e+00 1.93734258e+01
 8.27663626e+00 1.80236798e+01 9.03282846e+00 1.74519414e+01
 3.77386309e-01 1.66816760e+01]


You can also reserve location in memory without putting any default value

In [13]:
#create empty array without putting any default value (just reserve the space in memory) using the np.empty() function
vector3_reserved = np.empty((2,3)) #specify the shape in a tuple. In this case, 2 rows, three columns
print(vector3_reserved) #this will output zeros here but in other IDEs, it can show array of locations in memory

[[0. 0. 0.]
 [0. 0. 0.]]


**Creating Prefilled Array with Range of Numbers**

In [14]:
#similar to the python's range() function, but this arange() function (array range) outputs an array instead
x_axis = np.arange(0,10,2) #input start, stop, step like usual
print(x_axis)

[0 2 4 6 8]


The np.linspace() function for outputting an array containing a range but you can specify the count of numbers it should output spanning the full range from start to end

In [15]:
x_axis2 = np.linspace(1,20,10) #we are saying we want it to only output 10 numbers that spans the range provided (instead of providing 20 which the arange() would have done)
print(x_axis2) #this the output array with 10 elements containing numbers spanning between 1 and 20.0 (float)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


### Numpy Special Variable Values (NAN and INF)

In [16]:
a = np.nan #this is a NaN value (meaning not a number)
b = np.inf #this is an infinity number (like C# inf number)
print(a)
print(b)

nan
inf
