# Numpy Array Functions

In [4]:
import numpy as np

**SCALING AN ARRAY**

Append to the front or back of an array

In [5]:
arr1 = np.array([2,3,4,5])
appended_array = np.append(arr1,[9,8,7,6])

print(appended_array)

[2 3 4 5 9 8 7 6]


Insert into Arrays

In [6]:
inserted_array = np.insert(appended_array, 5, [11,22,33,44]) #this inserted the new array elements from index 5
print(inserted_array)

[ 2  3  4  5  9 11 22 33 44  8  7  6]


Deleting from an Array
> delete works in two ways.

> First is if no axis parameter is provided, then it will delete the element as the nth index in the array (even if its multi dimentional array).

In [15]:
nd_arr_0 = np.array([[2,3,4,5],
                   [9,8,7,6],
                   [3,4,0,1]])

new_arr = np.delete(nd_arr_0,2) #deletes the element at the given index. NOTE!! this is first flatten the array (since nd arrays must have uniform structure along the column, so if an element is deleted it can no longer retain its shape)
print(new_arr)

[2 3 5 9 8 7 6 3 4 0 1]


> Second is if the axis parameter is provided, then it will delete the whole row or column at that index (depending on the axis parameter)

In [17]:
nd_arr = np.array([[2,3,4,5],
                   [9,8,7,6],
                   [3,4,0,1]])

new_arr = np.delete(nd_arr, 1, axis=0) #we are saying delete the whole row with index 1 (same can also apply to column). This will retain a ndim shape since the number of columns are still consitent

print(new_arr)

[[2 3 4 5]
 [3 4 0 1]]


**RESHAPING AN ARRAY**

> Reshape

In [20]:
nd_arr = np.array([[2,3,4,5],
                   [9,8,7,6],
                   [3,4,0,1]])

new_shape_arr = np.reshape(nd_arr, (2,6)) #change the shape to a 2 x 6 shape
print(new_shape_arr)

[[2 3 4 5 9 8]
 [7 6 3 4 0 1]]


In [24]:
#resize() also works like reshaping but if used within the context of an array (i.e. arr.resize((shape))), it will modify the array without returning anything
new_size_arr = np.resize(nd_arr,(2,6)) #i'm not using it in the context of an array now, instead i'm calling it as a numpy function (so that it doesn't modify the original array)
print(new_size_arr)

[[2 3 4 5 9 8]
 [7 6 3 4 0 1]]


> Transposing.

Changing row to column and column to row

In [28]:
nd_arr = np.array([[2,3,4,5],
                   [9,8,7,6],
                   [3,4,0,1]])

transposed_arr = nd_arr.transpose() #change the column to rows and rows to columns
print(transposed_arr)

[[2 9 3]
 [3 8 4]
 [4 7 0]
 [5 6 1]]


You can also transpose by using arry.T (but this modifies the original array instead returning a new copy)

In [30]:
#using the .T expressioon transposes the original array instead of returning a transposed copy
nd_arr2 = np.array([[2,3,4,5],
                   [9,8,7,6]]).T

print(nd_arr2)

[[2 9]
 [3 8]
 [4 7]
 [5 6]]


> Swap Axis

In [37]:
#swap axis works the same way as tranpose but works best with array os higher layers than 2 as you can specify which two axis to swap instead of swapping the whole array's axis
nd_arr2 = np.array([[2,3,4,5],
                   [9,8,7,6]])

print(nd_arr2.swapaxes(0,0))

[[2 3 4 5]
 [9 8 7 6]]


**FLATTENING AN ARRAY**

Converting n dimensional arrays into 1D

In [38]:
nd_arr3 = np.array([[2,3,4,5],
                   [9,8,7,6]])

flattened_array = nd_arr3.flatten()

print(flattened_array)

[2 3 4 5 9 8 7 6]


ravel() works like flattening but modifies the original array instead of returning a flatened copy