# Numpy Array Concatenation

In [2]:
import numpy as np

### Concatenate arrays
> Can concatenate on row or column axis

In [17]:
class1_ages = np.array([23,4,5,75])
class2_ages = np.array([5,10,23,16])

In [18]:
#concatenate on row
school_ages = np.concatenate((class1_ages, class2_ages))
print(school_ages)

[23  4  5 75  5 10 23 16]


In [23]:
#example on n dimentaional array
nd_array1 = np.array([[12,3,5,6],
                      [9,24,9,1]])

nd_array2 = np.array([[43,25,67,5],
                      [1,35,7,4]])
conct_array_row = np.concatenate((nd_array1, nd_array2)) #by default this function concatenates on the row axis
print(conct_array_row)

[[12  3  5  6]
 [ 9 24  9  1]
 [43 25 67  5]
 [ 1 35  7  4]]


In [24]:
#you can also concatenate on the column axis
conct_array_col = np.concatenate((nd_array1, nd_array2), axis=1) #we have changed the axis param to let it know that is should sintead concatenate on the column axis
print(conct_array_col)

[[12  3  5  6 43 25 67  5]
 [ 9 24  9  1  1 35  7  4]]


**Stacing Arrays (instead of concatenating)**

In [29]:
stacked_arr = np.stack((nd_array1, nd_array2))
print(stacked_arr) #this returns one whole array with the two arrays inside it but seprated as they are wrapped in different parent arrays (thereby adding additional layer)
print(f"\nThe shape: \n{stacked_arr.shape}") #from the shape we can see that there is a superceeding layer of 2 layers

[[[12  3  5  6]
  [ 9 24  9  1]]

 [[43 25 67  5]
  [ 1 35  7  4]]]

The shape: 
(2, 2, 4)


### Split arrays
> Can split arrays either on row or column axis

In [30]:
giant_array = np.array([[12,3,5,6],
                        [9,24,9,1],
                        [43,25,67,5],
                        [1,35,7,4]])

In [ ]:
#split on row axis
split_array_row = np.split(giant_array,2,axis=0) #split the array into two part along the row axis. (this returns a list of two arrays)
print(split_array_row)

[array([[12,  3,  5,  6],
       [ 9, 24,  9,  1]]), array([[43, 25, 67,  5],
       [ 1, 35,  7,  4]])]


In [33]:
#split on col axis
split_array_col = np.split(giant_array,2,axis=1) #split the array into two part along the column axis. (its like drawing a vertical line in the middle of the ndim Array)
print(split_array_col)

[array([[12,  3],
       [ 9, 24],
       [43, 25],
       [ 1, 35]]), array([[ 5,  6],
       [ 9,  1],
       [67,  5],
       [ 7,  4]])]
